CREATE TABLE users (
    ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR(80),
    LAST_NAME VARCHAR(80),
    USER_NAME VARCHAR(30),
    EMAIL VARCHAR(80),
    CREDENTIAL VARCHAR(255),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE hibernate_sequence START 1;